
export const constantErr = {
    LOGIN_USER_NAME: "User is required",
    LOGIN_USER_PASSWORD: "Password is required",
    ORGANIZATION: "Organization is required",
    DEPARTMENT: "Department is required",
    PRODUCT: "Product is required",
    PRODUCT_ENV: "Product env is required",
    MODULE: "Module  is required",
    BUSSINESS_ELEMENT: "Business Element  is required",
    BUDGET: "Budget is required",
    DB_CATEGORY: "DB Category is required",
    LANDING_ZONE: "Landingzone is required",
    USER_NAME: "Name is required",
    USER_EMAIL: "Email is required",
    USER_PASSWORD: "Password is required",
    CLOUD: "Cloud name is required",
    DISPLAY_NAME: "Display name is required",
    ROLE_ARN: "Role arn is required",
    EXERNALID: "External id is required",
    BEARER_TOKEN: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJST0xFX0FOT05ZTU9VUyIsImF1dGgiOiJST0xFX0FOT05ZTU9VUyJ9.g_UGI84oTJAsde4-1Ye7-oDzb1Xkk3W6I3_b-rwvTlDxRrFhgjTPuBF7PSuBlUY9n6PmR7y5EcLnnn0JXNCuDA",
    START_DATE: "Start date is required",
    DATE_FORMATE: "Invalid date format. Please use yyyy-mm-dd format.",
    END_DATE: "End date is required",
}
